openapi: 3.1.0
info:
  title: ViseryaApp Taverns Actions
  version: 1.0.0
servers:
  - url: https://viserya.app
    description: Actions definition for creating taverns in Viserya
paths:
  /api/actions/create/tavern:
    post:
      operationId: createTavern
      tags:
        - Tavern Creation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                prompt:
                  type: string
                  description: The prompt for generating the tavern
                startPosition:
                  type: integer
                  description: The position in the template to start generating from.
                previousContent:
                  type: string
                  description: The content generated so far.
              required:
                - prompt
      responses:
        '200':
          description: Partial content generated.
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: string
                    description: The newly generated content.
                  nextPosition:
                    type: integer
                    description: The next position to continue generating from.
                  complete:
                    type: boolean
                    description: Indicates if the generation is complete.
  /api/actions/random/tavern:
    post:
      operationId: createRandomTavern
      tags:
        - Random Generation
        - Tavern Creation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                startPosition:
                  type: integer
                  description: The position in the template to start generating from.
                previousContent:
                  type: string
                  description: The content generated so far.
      responses:
        '200':
          description: Partial content generated.
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: string
                    description: The newly generated content.
                  nextPosition:
                    type: integer
                    description: The next position to continue generating from.
                  complete:
                    type: boolean
                    description: Indicates if the generation is complete.
  /api/actions/random/tavern/name:
    post:
      operationId: createRandomTavernName
      tags:
        - Random Generation
        - Tavern Name Creation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                startPosition:
                  type: integer
                  description: The position in the template to start generating from.
                previousContent:
                  type: string
                  description: The content generated so far.
      responses:
        '200':
          description: Partial content generated.
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: string
                    description: The newly generated content.
                  nextPosition:
                    type: integer
                    description: The next position to continue generating from.
                  complete:
                    type: boolean
                    description: Indicates if the generation is complete.
