import { Metadata } from 'next';
import { MainContainer } from '@viserya/ui';

export const metadata: Metadata = {
  title: 'Terms of Service - ViseryaApp',
};

export default function Terms() {
  return (
    <MainContainer>
      <h1 id="terms-of-service-viseryaapp">Terms of Service</h1>
      <p>
        Welcome to ViseryaApp. By using our API services, you agree to be bound
        by the following terms and conditions (&quot;Terms&quot;). Please read
        them carefully before using our services.
      </p>
      <h2 id="user-responsibilities">User Responsibilities</h2>
      <ul>
        <li>
          You are responsible for maintaining the security of your API keys and
          account information.
        </li>
        <li>
          You agree not to misuse the API services or use them for any unlawful
          activities.
        </li>
      </ul>
      <h2 id="use-of-services">Use of Services</h2>
      <ul>
        <li>
          The ViseryaApp API allows you to submit prompts to generate various
          content types (characters, adventures, locations, etc.).
        </li>
        <li>
          You may not use the services to infringe upon the intellectual
          property rights of others.
        </li>
      </ul>
      <h2 id="data-collection-and-privacy">Data Collection and Privacy</h2>
      <ul>
        <li>
          By using our services, you agree to the collection and use of personal
          data as outlined in our{' '}
          <a href="https://viserya.app/privacy">Privacy Policy</a>.
        </li>
        <li>
          We collect prompt data and usage data for the purposes of providing
          and improving services.
        </li>
      </ul>
      <h2 id="prohibited-conduct">Prohibited Conduct</h2>
      <ul>
        <li>
          You may not use the API to generate or disseminate any content that is
          illegal, offensive, or violates the rights of others.
        </li>
        <li>
          Automated or mass requests to the API that exceed rate limits are
          prohibited.
        </li>
      </ul>
      <h2 id="intellectual-property">Intellectual Property</h2>
      <ul>
        <li>
          All content generated by the API based on user prompts belongs to the
          user. However, ViseryaApp retains the rights to its software and API.
        </li>
        <li>
          You may not reverse-engineer or otherwise attempt to extract source
          code from our services.
        </li>
      </ul>
      <h2 id="liability">Liability</h2>
      <ul>
        <li>
          ViseryaApp provides its services &quot;as is&quot; without any
          warranties, express or implied.
        </li>
        <li>
          We are not liable for any damages resulting from your use of the API,
          including but not limited to data loss or service interruption.
        </li>
      </ul>
      <h2 id="termination">Termination</h2>
      <ul>
        <li>
          We reserve the right to terminate or suspend access to the API at our
          sole discretion for any reason, including breach of these Terms.
        </li>
      </ul>
      <h2 id="modifications">Modifications</h2>
      <ul>
        <li>
          ViseryaApp reserves the right to modify these Terms at any time.
          Continued use of the API services after such modifications indicates
          your acceptance of the new terms.
        </li>
      </ul>
      <h2 id="contact-information">Contact Information</h2>
      <p>
        For questions about these Terms, please contact us at{' '}
        <a href="mailto:support@viserya.app">support@viserya.app</a>.
      </p>
    </MainContainer>
  );
}
