openapi: 3.1.0
info:
  title: ViseryaApp Characters Actions
  version: 1.0.0
servers:
  - url: https://gpt-viserya-actions.vercel.app
    description: Actions definition for creating characters in Viserya
paths:
  /api/create/character:
    post:
      operationId: createCharacter
      tags:
        - Character Creation
      summary: Generate a character with a formatted markdown template and populate all placeholders. Proper names should be given using the Viselar language. Non-relevant or unpopulated sections should be removed.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                prompt:
                  type: string
                  description: The prompt for generating the character
                startPosition:
                  type: integer
                  description: The position in the template to start generating from.
                previousContent:
                  type: string
                  description: The content generated so far.
              required:
                - prompt
      responses:
        '200':
          description: Partial content generated.
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: string
                    description: The newly generated content.
                  nextPosition:
                    type: integer
                    description: The next position to continue generating from.
                  complete:
                    type: boolean
                    description: Indicates if the generation is complete.
  /api/random/character:
    post:
      operationId: createRandomCharacter
      tags:
        - Random Generation
        - Character Creation
      summary: Generate a random character with a formatted markdown template and populate all placeholders. Proper names should be given using the Viselar language. Non-relevant or unpopulated sections should be removed.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                startPosition:
                  type: integer
                  description: The position in the template to start generating from.
                previousContent:
                  type: string
                  description: The content generated so far.
      responses:
        '200':
          description: Partial content generated.
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: string
                    description: The newly generated content.
                  nextPosition:
                    type: integer
                    description: The next position to continue generating from.
                  complete:
                    type: boolean
                    description: Indicates if the generation is complete.
