openapi: 3.1.0
info:
  title: ViseryaApp Show Image Actions
  version: 1.0.0
servers:
  - url: https://gpt-viserya-actions.vercel.app
    description: Actions definition for creating images
paths:
  /api/show:
    post:
      operationId: showImage
      summary: Formats the image prompt.
      description: Takes a prompt as input and returns a formatted version of the prompt.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                prompt:
                  type: string
                  description: The input prompt to be formatted.
                subType:
                  type: string
                  enum:
                    - generalView
                    - battleEncounter
                    - characterPortrait
                    - charactersAreIndoors
                    - cityOverview
                    - overviewFromWithinTheCity
                    - socialEncounter
                    - withMultipleCharacters
              required:
                - prompt
      responses:
        '200':
          description: The formatted prompt.
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    description: The formatted version of the image prompt.
