openapi: 3.1.0
info:
  title: ViseryaApp Story Actions
  version: 1.0.0
servers:
  - url: https://gpt-viserya-actions.vercel.app
    description: Actions definition for writing stories in Viserya
paths:
  /api/write/story:
    post:
      operationId: writeStory
      tags:
        - Story Writting
      summary: Write a story with a formatted markdown template and populate all placeholders. Proper names should be given using the Viselar language. Non-relevant or unpopulated sections should be removed.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                prompt:
                  type: string
                  description: The prompt for generating the story
                startPosition:
                  type: integer
                  description: The position in the template to start generating from.
                previousContent:
                  type: string
                  description: The content generated so far.
              required:
                - prompt
      responses:
        '200':
          description: Partial content generated.
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: string
                    description: The newly generated content.
                  nextPosition:
                    type: integer
                    description: The next position to continue generating from.
                  complete:
                    type: boolean
                    description: Indicates if the generation is complete.
